CREATE TABLE IF NOT EXISTS master_events (
    msevId INT AUTO_INCREMENT PRIMARY KEY,
    msevName VARCHAR(255) NOT NULL,
    msevCreatedClientId VARCHAR(255) NOT NULL DEFAULT '',
    msevAppVersion VARCHAR(255) NOT NULL DEFAULT '',
    msevGuiVersion VARCHAR(255) NOT NULL DEFAULT '',
    msevMainVersion VARCHAR(255) NOT NULL DEFAULT '',
    msevCreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    msevUpdatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_msevName (msevName)
);