CREATE TABLE IF NOT EXISTS event_client_association (
    evcaId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    evcaMsevId INT UNSIGNED NOT NULL,
    evcaClntId VARCHAR(255) NOT NULL,
    evcaCreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    evcaUpdatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (evcaMsevId, evcaClntId),
    FOREIGN KEY (evcaMsevId) REFERENCES master_events(msevId) ON DELETE CASCADE
);