ALTER TABLE master_file_tagging ADD COLUMN mftgClientId VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mftgAppVersion VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mftgGuiVersion VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN mftgMainVersion VARCHAR(255) NOT NULL DEFAULT '';
