CREATE TABLE IF NOT EXISTS master_locations (
    mlocId INT AUTO_INCREMENT PRIMARY KEY,
    mlocMsevId INT NOT NULL,
    mlocName VARCHAR(255) NOT NULL,
    mlocCreatedClientId VARCHAR(255) NOT NULL DEFAULT '',
    mlocAppVersion VARCHAR(255) NOT NULL DEFAULT '',
    mlocGuiVersion VARCHAR(255) NOT NULL DEFAULT '',
    mlocMainVersion VARCHAR(255) NOT NULL DEFAULT '',
    mlocCreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mlocUpdatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_mlocMsevIdMlocName (mlocMsevId, mlocName),
    FOREIGN KEY (mlocMsevId) REFERENCES master_events(msevId) ON DELETE CASCADE ON UPDATE CASCADE
);