CREATE TABLE IF NOT EXISTS master_photographer (
    mptgId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mptgMsevId INT UNSIGNED NOT NULL,
    mptgName VARCHAR(255) NOT NULL,
    mptgCreatedClientId VARCHAR(255) NOT NULL DEFAULT '',
    mptgCreatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mptgUpdatedTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_mptgMsevIdMptgName (mptgMsevId, mptgName),
    FOREIGN KEY (mptgMsevId) REFERENCES master_events(msevId) ON DELETE CASCADE ON UPDATE CASCADE
);